version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        # Environment variable will be replaced by Code Pipeline
        TaskDefinition:  "arn:aws:ecs:us-east-1:815744959974:task-definition/churn:1"
        LoadBalancerInfo:
          # Container name, port should match the container name, port in task defintion json
          ContainerName: "churn"
          ContainerPort: 5000